# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG OWNER=jupyter
ARG BASE_CONTAINER=$OWNER/base-notebook:python-3.8.5
ARG JUPYTER_TOKEN=hi
ARG ENV_JUPYTER_ENABLE_LAB=no
ARG FLASK_HOST_PORT=http://camss-kd-flask:5000

FROM $BASE_CONTAINER

COPY ./camss-kd-jupyter-notebook-app/requirements.txt .

RUN pip install --no-cache-dir -r ./requirements.txt

# Exposes the default flask port
EXPOSE 8888
