version: '3.7'

services:
  jupyter-notebook:
    build: 
      context: .
      dockerfile: Dockerfile.jupyter
      args:
        - jupyter_port=${JUPYTER_PORT}
        - jupyter_dir=${JUPYTER_DIR}
    container_name: camss-kd-jupyter-notebook
    image: camss-kd-jupyter-notebook
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    networks:
      - camss-net
    volumes:
      - ./camss-kd-jupyter-notebook-app/src/dev:/home/jovyan/work
    restart: 
      always
    environment:
      - FLASK_HOST_PORT=${FLASK_HOST_PORT}
  flask-api:
    build: 
      context: .
      dockerfile: Dockerfile.flask
      args:
        - flask_port=${FLASK_PORT}
    container_name: camss-kd-flask
    image: camss-kd-flask
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    networks:
      - camss-net
    restart: 
      always
      
networks:
  camss-net:
