# Workflow name.
name: Deploy

# Run workflow on every push to main branch.
on: 
  push:
    branches:
      - main

# Workflow jobs.
jobs:
  jupyter-build:
    runs-on: ubuntu-latest 
    steps:
      # This actions copy the repository on the environment
      - uses: actions/checkout@v2 
      - name: Rename the heroku_jupyter.yml
        run: |
          ls -a
          mv heroku_jupyter.yml heroku.yml
          ls -a
      # This action deploys the content on Heroku
      - uses: isa-camss/CAMSS-User-Journeys@v1 
        with:
          # Heroku API key associated with provided user's email.
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: "camss-knowledge-discovery" 
          # The email address associated with Heroku account.
          heroku_email: "camss@nttdata.com" 
  
  flask-build:
    needs: python-build
    runs-on: ubuntu-latest # Setup an environment to run the action
    steps:
      - uses: actions/checkout@v2 # This actions copy the repository on the environment
      - name: Rename the heroku_flask.yml
        run: |
          ls -a
          mv heroku_flask.yml heroku.yml
          ls -a
      # This action deploys the content on Heroku
      - uses: isa-camss/CAMSS-User-Journeys@v1 
        with:
          # Heroku API key associated with provided user's email.
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: "camss-knowledge-discovery" 
          # The email address associated with Heroku account.
          heroku_email: "camss@nttdata.com" 
  