# Generate as much as .yml files for every operative systems the solution could be run, e.g.:
#   - linux.yml
#   - windows.yml

version: 1
formatters:
  brief:
    format: '[%(threadName)s] %(levelname)-7s [%(name)s] %(message)s'
  precise:
    format: '%(asctime)s [%(threadName)s] %(levelname)s [%(name)s.%(module)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  debug:
    class: com.nttdata.utils.loggers.handlers.DirFileHandler
    formatter: precise
    filename: debug.log
    max_bytes: 5242880
    backup_count: 20
    level: INFO
  console:
    class: logging.StreamHandler
    formatter: brief
    level: INFO
    stream: ext://sys.stdout
loggers:
  main:
    level: DEBUG
    handlers: [console, debug]
  com:
    level: DEBUG
    handlers: [console, debug]
    propagate: no
  org:
    level: DEBUG
    handlers: [ console, debug ]
    propagate: no
  apis:
    level: DEBUG
    handlers: [console, debug]
    propagate: no
