# Workflow name.
name: Deploy to heroku docker-compose image.

# Run workflow on every push to main branch.
on:
  push:
    branches: [master]

# Workflow jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out the repository.
      - name: Checkout
        uses: actions/checkout@v2

### ⬇ STRUCTURAL PART ⬇ ###
      - name: Build, Push and Release a docker-compose container to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          # Below variables for Heroku app.

          # The email address associated with Heroku account.
          email: ${{ secrets.HEROKU_EMAIL }}
          
          # Heroku API key associated with provided user's email.
          # Api Key is available under Heroku account settings.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          
          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # Dockerfile directory.
          dockerfile_directory: ./

          # Dockerfile name.
          dockerfile_name: docker-compose

          # Additional options of docker build command.
          docker_options: "--no-cache"

          # Select the process type for which you want the docker container to be uploaded.
          # By default, this argument is set to "web".
          process_type: web          
### ⬆ STRUCTURAL PART ⬆ ###